language: php

cache:
  directories:
    - vendor
    - bin

sudo: false

php:
  - 5.3

before_script:
  - composer self-update -n
  - composer install -n --prefer-dist -v

script:
  - bin/phpcs --standard=PSR2 --encoding=UTF-8 --ignore="*.db" --ignore="*.color",  --ignore="*.ttf" src/
    
