language: php

cache:
  directories:
    - vendor

php:
  - 5.4

before_script:
  - composer self-update -n
  - composer install -n --prefer-dist -v

script:
  - vendor/bin/phpcs --standard=PSR2 --encoding=UTF-8 --ignore="*.js" src/
  - vendor/bin/phpspec run -f pretty

after_failure:
  - cat app/logs/dev.log
  - cat app/logs/test.log
