language: php

cache:
  directories:
    - bin
    - vendor

sudo: false

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1


before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install -n --prefer-dist -v

script:
    - bin/phpcs --standard=PSR2 --encoding=UTF-8 --ignore="*.db,*.color,*.ttf" src/
